### ISSUE TITLE
Modify Pod Live View query to only fetch data from the pod's agent, rather than fanning out to all agents.

### ISSUE THREAD

**Issue by nserrino** [pixie-labs/pixie#115]
**Is your feature request related to a problem? Please describe.**
The Pod Live View currently looks at outbound traffic from a given pod. As a result, the query generated for this view will need to run on every agent in a cluster. For larger clusters, that makes this pod view less efficient. By omitting outbound traffic, we can make this view much faster. If it is important to see the traffic out of a pod, the Namespace Live View provides that information in a service graph. In addition, px/pod_edge_stats will show an even more detailed breakdown of traffic between two pods.

**Describe the solution you'd like**
Pod Live View to only run on a single agent.

**Describe alternatives you've considered**
Introducing another Pod live view for this purpose, a copy of the current one with outbound traffic removed. However, it currently seems better for the default Pod view to be fast and other existing views to be utilized for the outbound traffic information.

**Additional context**
N/A

**Comment by htroisi** [comment]
Verified fixed.
