### ISSUE TITLE
Console inoperable on browsers that block http requests from https pages

### ISSUE THREAD

**Issue by elsonrodriguez** [pixie-labs/pixie#12]
**Describe the bug**
Some browsers (example, Firefox) block http connections while on an https page. Currently the console UI tries to access vizier-proxy-service via `px proxy`, which serves on http://127.0.0.1:31068, this will trigger a blocking action.

**To Reproduce**

1. Open Pixie Console UI in Firefox
2. Start `px proxy`
3. Attempt to use Console UI
4. Open Firefox developer console to look for Javascript errors.

**Expected behavior**
The Pixie UI should be able to access its dependencies via some other connectivity as well (directly via nodeport, lb, etc) or a valid https cert and https connectivity should be given to the proxy service.

**Logs**

From Firefox javascript console.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:31067/graphql. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:31067/graphql. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:31067/graphql. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:31067/graphql. (Reason: CORS request did not succeed).
```

**App information (please complete the following information):**
- Pixie version `0.1.15+Distribution.acd8f53.20200207161509.1`
- K8s cluster version `Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.7-gke.23", GitCommit:"06e05fd0390a51ea009245a90363f9161b6f2389", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:45Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}`

┆Issue is synchronized with this [Jira Task](https://pixie-labs.atlassian.net/browse/PL-1648) by [Unito](https://www.unito.io/learn-more)

**Comment by htroisi** [comment]
Pixie's default data transfer mode is now the Passthrough Mode. For more information, check out:
- Pixie's high-level [architecture overview](https://docs.pixielabs.ai/about-pixie/how-pixie-works/).
- @aimichelle's detailed [blog post](https://blog.pixielabs.ai/blog/hybrid-architecture/hybrid-architecture/) on the subject.

@elsonrodriguez
