### ISSUE TITLE
Pod Live View is missing expected column (container) for CPU and memory widgets

### ISSUE THREAD

**Issue by nserrino** [pixie-labs/pixie#133]
**Describe the bug**
The vis.json expects a column called 'container' but it doesn't exist for the resource_timeseries table, causing the container to be omitted from the timeseries chart label.

**To Reproduce**
1. Go to the px/pod view and look at the CPU chart.

**Expected behavior**
The container name should show up in the legend.

**Comment by htroisi** [comment]
This bug was fixed by PR #134.
