### ISSUE TITLE
Support minikube 'none' driver

### ISSUE THREAD

**Issue by htroisi** [pixie-labs/pixie#150]
![image](https://user-images.githubusercontent.com/66266496/95774999-5b28b200-0c76-11eb-90d6-45456017b2e0.png)

reported by: @tristanz

**Comment by htroisi** [comment]
Pixie currently supports only the [`kvm2`](https://minikube.sigs.k8s.io/docs/drivers/kvm2/) driver for minikube. 

For anyone else running into this issue who is able to switch to the `kvm2` driver, see our [minikube install docs](https://docs.pixielabs.ai/installing-pixie/install-guides/minikube-setup/) for how to create a minikube cluster & deploy pixie.

**Comment by zasgar** [comment]
Closing as stale issue
