### ISSUE TITLE
Unable to parse gRPC http2 requests

### ISSUE THREAD

**Issue by ishanmkh** [pixie-labs/pixie#16]
// filed on behalf of @berilane-te   @shashank-te 

**Describe the bug**
Unable to see parsed protobuf data for Thanos requests

**To Reproduce**

1. Ran the "sample http_events" script

2. Ran the query below

```
t1 = px.DataFrame(table='http_events', select=['time_', 'remote_addr', 'remote_port', 'http_resp_status', 'http_resp_message', 'http_resp_body', 'http_resp_latency_ns', 'http_major_version'], start_time='-30s')
t1.http_resp_latency_ms = t1.http_resp_latency_ns / 1.0E6
t1 = t1[t1['http_major_version'] == 2]
t2 = t1.drop(columns=['http_resp_latency_ns']).head(n=100)
px.display(t2)
```

**Expected behavior**
Expected to see parsed data.

**Logs**
n/a

**App information (please complete the following information):**
- Pixie version: v0.1.18

┆Issue is synchronized with this [Jira Task](https://pixie-labs.atlassian.net/browse/PL-1647) by [Unito](https://www.unito.io/learn-more)

**Comment by htroisi** [comment]
Quick update: the root cause of this issue has not yet been discovered, but we have been able to reproduce the issue in a test environment (https://pixie-labs.atlassian.net/browse/PP-1897).

**Comment by zasgar** [comment]
This issue is now resolved.
