### ISSUE TITLE
px deploy failed flatcar linux kubernetes cluster

### ISSUE THREAD

**Issue by 4ss3g4f** [pixie-labs/pixie#160]
**Describe the bug**
$ px deploy (failed)

**To Reproduce**
fatal failed to fetch vizier versions error=open /home/core/.pixie/auth.json: no such file or directory

**Expected behavior**
pixie should be running properly

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
Please attach the logs by running the following command:
px deploy
./px collect-logs
```

**App information (please complete the following information):**
- Pixie version
- K8s cluster version v1.19.2

fatal failed to fetch vizier versions error=open /home/core/.pixie/auth.json: no such file or directory

Please help


**Additional context**
Add any other context about the problem here.

**Comment by htroisi** [comment]
Hey - thanks for trying out Pixie! 

This looks like an authentication error. Could you try running `px auth login`, and then re-try `px deploy`? The error message isn't very clear here and we've submitted a fix to improve it for future users - so thank you for catching this! Also, if you have a confirm that this fixes your issue, that would be appreciated.

**Comment by 4ss3g4f** [comment]
@htroisi ,
![image](https://user-images.githubusercontent.com/22811935/96551181-1a671380-12dc-11eb-8087-50d49017a420.png)

![image](https://user-images.githubusercontent.com/22811935/96551224-27840280-12dc-11eb-8c03-64b4edbd779d.png)

`core@manager-01 /opt/bin $ sudo bash -c "$(curl -fsSL https://withpixie.ai/install.sh)"

  ___  _       _
 | _ \(_)__ __(_) ___
 |  _/| |\ \ /| |/ -_)
 |_|  |_|/_\_\|_|\___|

==> Info:
Pixie gives engineers access to no-instrumentation, streaming &
unsampled auto-telemetry to debug performance issues in real-time,
More information at: https://www.pixielabs.ai.

This command will install the Pixie CLI (px) in a location selected
by you, and performs authentication with Pixie's cloud hosted control
plane. After installation of the CLI you can easily manage Pixie
installations on your K8s clusters and execute scripts to collect
telemetry from your clusters using Pixie.

Docs:
  https://work.withpixie.ai/docs


==> Terms and Conditions https://www.pixielabs.ai/terms
I have read and accepted the Terms & Conditions [y/n]: y


==> Installing PX CLI:
Install Path [/root/bin]: /opt/bin

==> Authenticating with Pixie Cloud:
Pixie CLI
Opening authentication URL: https://work.withpixie.ai:443/login?local_mode=true&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth_complete
Starting browser
Fetching refresh token ...
Failed to perform browser based auth. Will try manual auth error=browser failed to open

Please Visit: 
         https://work.withpixie.ai:443/login?local_mode=true

Copy and paste token here: 0nPnUahE3coGxdxjocgOexL8tA_FMhrl
Fetching refresh token
[0028] FATAL Failed to login error=Failed to login: organization not found, please register.


FAILED to authenticate with Pixie cloud. 
  You can try this step yourself by running px auth login.
  For help, please contact support@pixielabs.ai or join our community slack/github"


==> Next steps:
- PX CLI has been installed to: /opt/bin. Make sure this directory is in your PATH.
- Run px deploy to deploy pixie on K8s.
- Run px help to get started, or visit our UI: https://work.withpixie.ai
- Further documentation:
    https://work.withpixie.ai/docs`

**Comment by 4ss3g4f** [comment]
@htroisi ,
![image](https://user-images.githubusercontent.com/22811935/96551495-93666b00-12dc-11eb-8ecb-92eb6cf58f1c.png)

Still not able to install pixie, with **px auth login**

**Comment by htroisi** [comment]
@4ss3g4f - I'm sorry that my previous advice wasn't correct. Can you confirm that, as a separate step, you have signed-up for Pixie on our [product page](https://work.withpixie.ai/) using a google or gsuite account? 

Usually this sign-up step is part of the browser based authentication flow, but in your case it looks like the browser based auth failed and this needs to be done as a separate step.

**Comment by 4ss3g4f** [comment]
@htroisi ,
![image](https://user-images.githubusercontent.com/22811935/96670308-3248a100-1389-11eb-9ec3-4c835380d1b2.png)

I had already login with google account, you can't have pixie token before you sign in,

Still can not install pixie

**Comment by htroisi** [comment]
@4ss3g4f - Can you confirm that you are using this same naruto.as****f@gmail.com account to authenticate / get the token when you run `px auth login` in the command line? 

Because the authentication is manual, a token is generated for any legal google account, and it does not check that the google account is registered with Pixie. We've run into a few cases were people have accidentally used a different account to authenticate than they registered with, so I want to make sure that's not what's happening here.

**Comment by 4ss3g4f** [comment]
@htroisi ,
i guess i can not comfirm that, i guess i will just have to used other tools for flatcar linux

**Comment by htroisi** [comment]
@4ss3g4f - I am so sorry that your experience with Pixie so far has not been great and I apologize for that. However, I think you will really like the insights you can instantly get from Pixie's no-instrumentation observability platform if we can resolve this installation bug. Before you give up on us, would you be willing to message me (hannah troisi) on our [community slack channel](https://slackin.withpixie.ai/) and I can debug this in real time via chat or zoom?

**Comment by htroisi** [comment]
Closing this issue because it's been more than 2 weeks since the last response. @4ss3g4f, if you are still having trouble installing Pixie please re-open this issue or reach out on our [slack](https://slackin.withpixie.ai/).
