### ISSUE TITLE
Pixie install doesn't seem to support OIDC authentication scheme

### ISSUE THREAD

**Issue by jpapejr** [pixie-labs/pixie#181]
**Describe the bug**
Upon running `px deploy`, I'm faced with the following error:

``` shell
jtpape@johns-mbp Downloads % px deploy
Pixie CLI

Running Cluster Checks:
 ⠹    Kernel version > 4.14.0 
[0000] FATAL Could not create k8s clientset error=no Auth Provider found for name "oidc"
```

**To Reproduce**
1. Create a cluster on IBM Cloud or any other provider that uses OIDC authentication for k8s clusters
2. Run `bash -c "$(curl -fsSL https://withpixie.ai/install.sh)"` locally
3. Post install, run `px deploy`

**Expected behavior**
Expectation is that k8s client is able to be created and deployment succeeds (or at least progresses to next error condition)

**Screenshots**
Will provide, if required. 

**Logs**
Please attach the logs by running the following command:
``` shell
jtpape@johns-mbp Downloads % px collect-logs
Pixie CLI
[0000] FATAL Could not create k8s clientset error=no Auth Provider found for name "oidc"
```

**App information (please complete the following information):**
- Pixie version `0.3.15+Distribution.d906330.20201023235014.1`
- K8s cluster version `v1.19.4`

**Comment by zasgar** [comment]
@jpapejr, thanks for filling this issue. We have resolved it on our end. The CLI update should be going out tomorrow.

**Comment by zasgar** [comment]
Fix has been released.
