### ISSUE TITLE
Pixie with Minikube locally on Mac: "FATAL Timed out waiting for cluster ID assignment"

### ISSUE THREAD

**Issue by ahunger603** [pixie-labs/pixie#182]
**Describe the bug**
Following the instructions on the Pixie Labs website, in conjunction with the Minikube website setup, I'm attempting to get this working on a local Kube cluster. When running `px deploy`, I receive "FATAL Timed out waiting for cluster ID assignment" during the step "Waiting for Cloud Connector to come online".  I am on a MacBook Pro, running Catalina. 

**To Reproduce**
1. Be on MacBook Pro, running Catalina (If relevant)
2. Setup Minikube and start cluster using the suggested Hyperkit driver.
3. Attempt to deploy Pixie.

**Expected behavior**
The expected behavior would be a successful deploy.

**Screenshots**
![Screen Shot 2020-12-16 at 3 51 12 PM](https://user-images.githubusercontent.com/15317289/102421160-a33abc80-3fb8-11eb-8cd1-7cbea08e552b.png)

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
Pixie CLI
[0000]  WARN Failed to log pod: cert-provisioner-job-8l6nk error=container "provisioner" in pod "cert-provisioner-job-8l6nk" is waiting to start: trying and failing to pull image
[0000]  WARN Failed to log pod: vizier-cloud-connector-5485ff7c95-5tmrb error=container "app" in pod "vizier-cloud-connector-5485ff7c95-5tmrb" is waiting to start: ContainerCreating
```

**App information**
- Pixie version
0.3.15+Distribution.d906330.20201023205014.1

- K8s cluster version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876

**Additional Informantion**
- I was not on a VPN during this process.

**Comment by ahunger603** [comment]
Problem was solved by doubling the resources I had previous given Minikube!

**Comment by oazizi000** [comment]
Can you share the resources that you ended up using with minikube?

**Comment by ahunger603** [comment]
@oazizi000 While debugging a different issue running Minikube, I reduced it to `cpus=2 and memory=3000`, when I boosted to back to the recommended values `cpus=4 and memory=6000`, it was working 🙂

**Comment by AngerM-DD** [comment]
If anyone else runs into this and just increasing the memory doesn't help: It appears minikube w/ containerd does NOT work. minikube with docker does. So do NOT pass `--container-runtime=containerd` when you create your minikube for testing.

**Comment by kaisubr** [comment]
Note, for newer versions of pixie, I needed `cpus=4 and memory=8000`. Thanks, this thread helped to narrow down the issue :)

**Comment by jberryman** [comment]
any other possibilities? I haven't set any resource limits anywhere, using k3s. For a brief moment everything was working, now I'm finding `px deploy` failing again, as above. I'm sure it's my fault

**Comment by ddelnano** [comment]
@jberryman can you provide the logs from `px collect-logs`?

**Comment by jberryman** [comment]
@ddelnano certainly, thanks!
[pixie_logs_20240910203406.zip](https://github.com/user-attachments/files/16956386/pixie_logs_20240910203406.zip)

**Comment by jberryman** [comment]
Really appreciate the offer. I did need to add this to my manifest files so that I could resolve internet names. Not sure if that's expected:

```
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        options:
          - name: ndots
            value: "5"
```

meantime I have nuked k3s and am hoping that k0s might work better ....
