### ISSUE TITLE
minikube example in Quick Start doesn't work

### ISSUE THREAD

**Issue by DanStadlerNewRelic** [pixie-labs/pixie#194]
**Describe the bug**
I have followed all the instructions here: 
https://docs.pixielabs.ai/installing-pixie/quick-start/#start-a-demo-app
https://docs.pixielabs.ai/installing-pixie/quick-start/#4.-deploy-pixie

The demo app is available from the browser, and K8s Dashboards shows everything green. However I don't see any of the lines lighting up between the nodes, in the main cluster chart in the Pixie UI.

**To Reproduce**
Follow the 2 above steps. 
I am on OSX 10.15.7
here is my minikube start : minikube start --driver=hyperkit --cpus=4 --memory=6000 -p=stadler-pixiedemo

**Expected behavior**
I expected to see lines light up between the nodes in the main cluster UI. Please see attached screenshot.

**Screenshots**
Please see attached.

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```

**App information (please complete the following information):**
Running Cluster Checks:
 ✔    Kernel version > 4.14.0
 ✔    Cluster type is supported
 ✔    K8s version > 1.12.0
 ✔    Kubectl > 1.10.0 is present
 ✔    User can create namespace
Installing version: 0.5.21

**Additional context**
I have spoken with Hannah Troisi about this issue.

attachments:

<img width="1533" alt="expecting-green-lines" src="https://user-images.githubusercontent.com/18580583/105551610-bcb9dd00-5cb7-11eb-9eab-2cc7aa359bc2.png">

[pixie_logs_20210122134057.zip](https://github.com/pixie-labs/pixie/files/5858760/pixie_logs_20210122134057.zip)

**Comment by htroisi** [comment]
The primary issue here is that the cluster keeps cycling between healthy/unhealthy state. This issue is 100% reproducible following the instructions in the Quick Start doc. 

There is also an unrelated stirling crash seen in `vizier-pem-bt4qx__pem.log`, being tracked in Jira ticket PP-2400.

**Comment by htroisi** [comment]
Update: [Pixie Vizier `v0.5.23`](https://docs.pixielabs.ai/reference/admin/product-updates/#pixie-platform-%22vizier%22) (released 2.1.21) fixes the memory corruption bug that caused the PEMs to frequently crash, resulting in the cluster cycling between the healthy/unhealthy state.
