### ISSUE TITLE
kops (aws backed) cluster unhealthy viziers

### ISSUE THREAD

**Issue by DanStadlerNewRelic** [pixie-labs/pixie#195]
**Describe the bug**
Pixie does not correctly deploy into a KOPS (k8s on AWS - https://github.com/kubernetes/kops ) cluster.

**To Reproduce**
1. Deploy KOPS mostly with defaults. I increased the number of workers to 4 but otherwise did not change anything.
2. Install the NR K8s integration
3. Deploy the sock-shop demo app.  (everything looks good up to this point.)
4. Deploy pixie from the command line.

Look in NR K8s: several viziers in critical state. (click in for Events and Logs for more details).

**Expected behavior**
Expected to see the demo of the Pixie UI showing nodes connected by green lines.

**Screenshots**
<img width="1271" alt="some-logs-from-vizier" src="https://user-images.githubusercontent.com/18580583/105782603-b16de800-5f29-11eb-818d-64e03d85e691.png">
<img width="1625" alt="looking-at-one-vizier" src="https://user-images.githubusercontent.com/18580583/105782605-b29f1500-5f29-11eb-8dff-974c33a44e41.png">
<img width="1066" alt="details-of-one-worker" src="https://user-images.githubusercontent.com/18580583/105782606-b29f1500-5f29-11eb-83b3-d0e9cbcbf2a9.png">
<img width="1349" alt="after-deploying-pixie" src="https://user-images.githubusercontent.com/18580583/105782608-b337ab80-5f29-11eb-94cd-92f14fd084ff.png">
<img width="1622" alt="after-deploying-sock-shop" src="https://user-images.githubusercontent.com/18580583/105782609-b337ab80-5f29-11eb-9966-28f759bf4b04.png">

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```
[pixie_logs_20210125140910.zip](https://github.com/pixie-labs/pixie/files/5870381/pixie_logs_20210125140910.zip)

**App information (please complete the following information):**
dstadler$ px deploy
Pixie CLI

Running Cluster Checks:
 ✔    Kernel version > 4.14.0
 ✔    Cluster type is supported
 ✔    K8s version > 1.12.0
 ✔    Kubectl > 1.10.0 is present
 ✔    User can create namespace
Installing version: 0.5.21
Generating YAMLs for Pixie
Deploying Pixie to the following cluster: apnortheast1a.stadler-k8s.com

Is the cluster correct? (y/n) [y] : y
Found 4 nodes
 ✔    Creating namespace
 ✔    Deleting stale Pixie objects, if any
 ✔    Deploying secrets and configmaps
 ✔    Deploying Cloud Connector
 ✔    Waiting for Cloud Connector to come online
Waiting for Pixie to pass healthcheck
 ✔    Wait for PEMs/Kelvin
 ✔    Wait for healthcheck

==> Next Steps:

Run some scripts using the px cli. For example:
- px script list : to show pre-installed scripts.
- px run px/service_stats : to run service info for sock-shop demo application (service selection coming soon!).

Check out our docs: https://work.withpixie.ai/docs.

Visit : https://work.withpixie.ai to use Pixie's UI.

**Additional context**
Have spoken to Hannah Troisi about this via NR Slack.

**Comment by htroisi** [comment]
FYI - the pem logs show the same Stirling issue as https://github.com/pixie-labs/pixie/issues/194

`terminate called after throwing an instance of 'std::bad_variant_access'`

**Comment by DanStadlerNewRelic** [comment]
Update: I was able to get past this after I made 2 changes (not sure which one did the trick):
- revert from Ubuntu 20 to Ubuntu 18
- change host type from t3.medium to t3.large

**Comment by htroisi** [comment]
Update: [Pixie Vizier `v0.5.23`](https://docs.pixielabs.ai/reference/admin/product-updates/#pixie-platform-%22vizier%22) (released 2.1.21) fixes the memory corruption bug that caused the PEMs to frequently crash, resulting in the cluster cycling between the healthy/unhealthy state.
