### ISSUE TITLE
Improve robustness to k8s leader election failures

### ISSUE THREAD

**Issue by nirvana620** [pixie-labs/pixie#207]
**Describe the bug**
Pixie is unstable and will eventually crash without being able to self-recover on EKS 1.18.

However, after testing on EKS 1.16 (3 separate clusters) Pixie runs flawlessly.

**To Reproduce**
Helm install or px deploy on an EKS 1.18 cluster, there's very little traffic on this cluster with plenty of resources. After an undefined amount of time (60m to 10hours) the Connector and Vizier deployments will be in a constant crash loop state.

After testing on EKS 1.16 the issue is no longer relevant. I will eventually be upgrading the 1.18 cluster to 1.19 and testing Pixie's stability.

**Logs**
`E0223 16:21:06.009106 1 leaderelection.go:356] Failed to update lock: context deadline exceeded
I0223 16:21:06.026331 1 leaderelection.go:277] failed to renew lease pl/cloud-conn-election: timed out waiting for the condition
E0223 16:21:06.026515 1 leaderelection.go:296] Failed to release lock: resource name may not be empty
time="2021-02-23T16:21:06Z" level=error msg="leadership lost" id=vizier-cloud-connector-5454678848-7qnl9
panic: leadership lost`

**App information (please complete the following information):**
- Pixie version: latest, 0.5.27
- K8s cluster version: 1.18 and 1.16

**Comment by nirvana620** [comment]
Looks like the issue is still relevant on 1.16. 2/3 environments are working well and our QA environment vizier deployments are now in a constant crashing state.

**Comment by nirvana620** [comment]
After running the application for 2 days, Pixie is only stable on 2 environments. All four environments pixie is loaded on are on EKS, however the main difference is...

Stable: Using m5a.xlarge
Unstable: m5a.large

**Comment by htroisi** [comment]
Internal ticket: https://pixie-labs.atlassian.net/browse/PP-2470

**Comment by aimichelle** [comment]
We had a pretty short timeout specified for the leader election (1s), which is generally too short for most k8s clusters. We've upped that timeout to 5s, and have gotten less reports of this problem. 

Going to close this issue for now, but please feel free to reopen if anyone is still consistently hitting this issue!
