### ISSUE TITLE
px/cluster, px/namespace and other scripts should use process_stats table to create list of services

### ISSUE THREAD

**Issue by nserrino** [pixie-labs/pixie#210]
**Describe the bug**
In some scripts, the list of services is created from process_stats, which will always be present. In others, it is created from http_events. The problem with http_events is not all services have http_events, so they will be incorrectly omitted. We should instead generate the list of services with process_stats (and the same should be true of pods and other entities besides services).

**To Reproduce**
1. Have a service which does not have http events
2. Go to px/namespace and see that it does not show up for that service's namespace
3. Go to px/services and see that it does show up in that script

**Expected behavior**
Services without http_events should show up in relevant lists

**Comment by zasgar** [comment]
Closing as stale issue
