### ISSUE TITLE
Compile error, missing HTTP Tables.

### ISSUE THREAD

**Issue by WarpWing** [pixie-labs/pixie#241]
**Describe the bug**
Cannot run any scripts due to a HTTP Event module not found?
```shell
Script compilation failed: L222 : C22  Table 'http_events' not found.\n
```

**To Reproduce**
Install fresh version of Pixie on Minikube Cluster

**Expected behavior**
Pixie scripts to execute 

**Screenshots**
![image](https://user-images.githubusercontent.com/28925758/117092050-2623a000-ad2b-11eb-8722-f0409630a8b9.png)
![image](https://user-images.githubusercontent.com/28925758/117092069-2f147180-ad2b-11eb-9488-ec4e6ee8cc14.png)

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs (See Zip File) 
```
[pixie_logs_20210505024739.zip](https://github.com/pixie-labs/pixie/files/6424858/pixie_logs_20210505024739.zip)
**App information (please complete the following information):**
- Pixie version: 0.5.3+Distribution.0ff53f6.20210503183144.1
- K8s cluster version: v1.20.2

**Comment by zasgar** [comment]
@WarpWing, thanks for reporting the issue. 

We have a poor error message and it's something we are tracking to fix. The issue over here is that we are not able to install the probes b/c it looks like we could not able to properly load the kernel headers. I'm adding @oazizi000 to help debug.

**Comment by oazizi000** [comment]
@WarpWing I'm looking into this. While we investigate on a fix, you can try installing the Linux headers as a workaround? On Ubuntu, it's typically a command like `sudo apt install linux-headers-$(uname -r)`.

**Comment by WarpWing** [comment]
> @WarpWing I'm looking into this. While we investigate on a fix, can you try installing the Linux headers as a workaround? On Ubuntu, it's typically a command like `sudo apt install linux-headers-$(uname -r)`.

@oazizi000  Sure! Let me make sure that is the right command. I'm pretty sure linux headers are installed so let me look into and respond with a screenshot

**Comment by WarpWing** [comment]
![image](https://user-images.githubusercontent.com/28925758/117135772-6871cf00-ad75-11eb-8578-f99f1250a8fe.png)
@oazizi000 So I've already have the Linux headers it seems.

**Comment by WarpWing** [comment]
Right now, I'm going to go do a clean reinstall and update what the result is

**Comment by oazizi000** [comment]
@WarpWing Thanks for confirming the Linux headers are installed. According to the logs, Pixie can't locate the Linux headers. Can you confirm the following directory exists on your host machine: `/lib/modules/5.4.0-72-generic`

Also, can you provide the following information, so we can try to reproduce:
1. Host OS version.
2. Your minikube version.
3. The `minikube start` command you used to create the minikube cluster.

**Comment by WarpWing** [comment]
> @WarpWing Thanks for confirming the Linux headers are installed. According to the logs, Pixie can't locate the Linux headers. Can you confirm the following directory exists on your host machine: `/lib/modules/5.4.0-72-generic`
> 
> Also, can you provide the following information, so we can try to reproduce:
> 
>     1. Host OS version.
> 
>     2. Your minikube version.
> 
>     3. The `minikube start` command you used to create the minikube cluster.

1.  Ubuntu 20.04.1 LTS x86_64
2. minikube version: v1.18.1
commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc
3.
```shell
minikube start --nodes 4 -p forge
```
(Kubernetes Node Images)
![image](https://user-images.githubusercontent.com/28925758/117194944-b3f69e00-adb2-11eb-8a71-4b01c547ae84.png)

Maybe it's a docker driver issue?

**Comment by WarpWing** [comment]
Also the proof of linux headers existence
![image](https://user-images.githubusercontent.com/28925758/117195076-d8eb1100-adb2-11eb-979a-7ba65748f0d7.png)

**Comment by oazizi000** [comment]
> Maybe it's a docker driver issue?

Ahh...yes. We only support the kvm2 driver right now, so you'll want to try something like this:

```
minikube start --driver=kvm2 --cpus=4 --memory=6000 -p=<cluster-name>
```

**Comment by oazizi000** [comment]
Btw, how were you deploying? The `px deploy` command should have detected that minikube was not running the kvm2 driver and given an error message. If it didn't we'll want to look into that.

**Comment by WarpWing** [comment]
> Btw, how were you deploying? The `px deploy` command should have detected that minikube was not running the kvm2 driver and given an error message. If it didn't, we'll want to look into that.

Oh I just did the old --check=false flag because I didn't think it would matter but now that I think about it, that's just on me

**Comment by WarpWing** [comment]
I'll close this now, thanks for the assistance!
