### ISSUE TITLE
E: Unable to locate package px

### ISSUE THREAD

**Issue by 1711raggu** [pixie-labs/pixie#256]
**Describe the bug**
PX CLI has been installed to: /home/prox.cdn/devops/bin. I can see the file "px"
However, I couldn't deploy "px" using command "px deploy"

Error Message:
E: Unable to locate package px

I did try installing "px" using "apt install px" this also didn't work.

**To Reproduce**
1. Comman used to istall pixie: bash -c "$(curl -fsSL https://withpixie.ai/install.sh)"

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```

**App information (please complete the following information):**
- Pixie version
- K8s cluster version

**Additional context**

**Comment by htroisi** [comment]
@1711raggu - It looks like you were able to deploy Pixie based on the next issue you filed (#257)? Can we close this issue?

**Comment by 1711raggu** [comment]
I could able to install  using other method specified in the document. But could not install not using  >>> bash -c "$(curl -fsSL https://withpixie.ai/install.sh)"
