### ISSUE TITLE
Add disable auto-update in Helm chart

### ISSUE THREAD

**Issue by fryckbos** [pixie-labs/pixie#267]
**Is your feature request related to a problem? Please describe.**
I would like to have a bit more control over the auto-update and would like to disable it when installing with the Pixie Helm chart.

**Describe the solution you'd like**
A new variable in the Helm chart that disables the auto-update.

**Describe alternatives you've considered**
/

**Comment by aimichelle** [comment]
Change has rolled out in vizier version 0.7.10.
