### ISSUE TITLE
Automatically install latest Pixie version from the Helm chart

### ISSUE THREAD

**Issue by fryckbos** [pixie-labs/pixie#270]
**Is your feature request related to a problem? Please describe.**
I'm running an older version of the Helm chart, which makes it so that the previous Pixie version is installed first. Immediately after that, Pixie is updated. 

**Describe the solution you'd like**
It would be nice if it installed the latest version right away, unless I'm specifying a specific version and have auto-update disabled.

**Describe alternatives you've considered**
Wait longer upon installation to see my data coming in :-).

**Comment by aimichelle** [comment]
We have a new set of helm charts for the Vizier operator, which will automatically pick up the latest version.
