### ISSUE TITLE
Pixie Development Environment Error

### ISSUE THREAD

**Issue by wburnett** [pixie-labs/pixie#274]
**Describe the bug**
While attempting to bring up a PxL development environment, the `make dev` command failed. Following the documentation here: https://docs.pixielabs.ai/tutorials/script-dev-environment/
**To Reproduce**
1. `git clone https://github.com/pixie-labs/pixie.git`
2. `cd pixie/src/pxl_scripts`
3. `make dev`
4. When bazel is not installed: ```~/I/p/s/pxl_scripts ❯❯❯ make dev                                                                                                                                                                                        main ⬇ ✱
Makefile:27: *** "No bazel in PATH".  Stop.```
When Bazel is installed: ```make dev                                           main
./watch.sh
==> Running dev server for pxl_scripts
Open chrome console and add:  localStorage.setItem('px-custom-oss-bundle-path', 'http://127.0.0.1:8000/bundle-oss.json')
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
DEBUG: /private/var/tmp/_bazel_wyatt.burnett/c55c92384ece3d8af9d527e951d6d23f/external/bazel_gazelle/internal/go_repository.bzl:189:18: com_github_emicklei_go_restful: gazelle: finding module path for import github.com/mjibson/appstats: go get: module github.com/mjibson/appstats: git ls-remote -q origin in /private/var/tmp/_bazel_wyatt.burnett/c55c92384ece3d8af9d527e951d6d23f/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/444aab7ea271b6130ec26c66b91d9ad882ee59ce867f2107d31a0875343c64c2: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
INFO: Analyzed target //src/pixie_cli:px (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_wyatt.burnett/c55c92384ece3d8af9d527e951d6d23f/external/com_google_protobuf/BUILD:480:10: Linking external/com_google_protobuf/protoc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/external/com_google_protobuf/protoc-2.params
Use --sandbox_debug to see verbose messages from the sandbox
clang: error: unsupported option '-static-libgcc'
Target //src/pixie_cli:px failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.526s, Critical Path: 0.29s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
make[1]: *** [bundle-oss.json] Error 1```

**Expected behavior**
Create a development environment exposed on port 8000 as outlined in the documentation

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```
[pixie_logs_20210524143120.zip](https://github.com/pixie-labs/pixie/files/6534311/pixie_logs_20210524143120.zip)

**App information (please complete the following information):**
- Pixie version: 0.5.9+Distribution.c49ec7f.20210513144415.1
- K8s cluster version: 1.19.9-gke.1400
--

<br class="Apple-interchange-newline">

**Additional context**
When reporting the error on Slack, Zain Asgar directed me here.

**Comment by vihangm** [comment]
Should be fixed by 2f1b62ac7dcc451dd5c3bf8debbc9eafbd7fd5af
