### ISSUE TITLE
Include ported bpftrace tools pxl scripts - part 1

### ISSUE THREAD

**Issue by avwsolutions** [pixie-labs/pixie#291]
**Describe the use-case**
Ported bpftrace functionality toward Pxl scripts.  Currently the following are included. 

- syncsnoop
- oomkill
- nap_time
- dcsnoop
- capable
- mdflush

Still working on part 2, which are not yet working since the debugging of these scripts is hard .Would be great to have this improved over time. 

These are the first "working" releases.

**Example scenario**
Every bpftrace script has their own purpose to troubleshoot your system.  See also manifest.yaml for this info.

More details see https://github.com/iovisor/bpftrace/blob/master/tools

- syncsnoop -  Tracing file system sync events.
- oomkill - Traces the Linux out-of-memory (OOM) killer and shows basic details on one line per OOM kill.
- nap_time - Tracing application sleeps via the nanosleep(2) syscall.
- dcsnoop - Traces directory entry cache (dcache) lookups.
- capable -  Traces calls to the kernel cap_capable() function, which does security capability checks.
- mdflush - Traces flushes at the md driver level, and prints details.

**Desired output**
Currently simple Results table is included.

**Comment by aimichelle** [comment]
This has been merged in. Closing.
