### ISSUE TITLE
Support collecting https data encrypted with go tls?

### ISSUE THREAD

**Issue by Masterlvng** [pixie-labs/pixie#295]
Hi
As the doc "https://docs.px.dev/about-pixie/data-sources/" said,  it seems to support collecting https data encrypted with go tls. 
But how to do it? Any Scripts or doc?
Thanks

**Comment by zasgar** [comment]
@Masterlvng, we use uprobes to instrument the Go Libraries. You can look at the PxL script 'px/http_data'. Please, re-open if you have any other questions.
