### ISSUE TITLE
Missing config_manager_server_image in self-hosted deployment.

### ISSUE THREAD

**Issue by HighWatersDev** [pixie-labs/pixie#299]
**Describe the bug**
When installing Pixie using self-hosted method, config-manager-server fails to pull the container image: gcr.io/pixie-oss/pixie-dev/cloud/config_manager_server_image.

This line doesn't specify a tag, so it's looking for 'latest' tag: https://github.com/pixie-labs/pixie/blob/8fce081e2d1e00490016a6beb184cd2aafbe1e76/k8s/cloud/base/config_manager_deployment.yaml#L17

Looking at grc.io repository, it's missing image with 'latest' tag: https://console.cloud.google.com/gcr/images/pixie-oss/GLOBAL/pixie-dev/cloud/config_manager_server_image?gcrImageListsize=30&gcrImageListquery=%255B%255D

**To Reproduce**

Following these steps: https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud, step 8.

**Comment by vihangm** [comment]
This has been fixed! Let us know if you run into other issues.
