### ISSUE TITLE
Drill Down in the UI

### ISSUE THREAD

**Issue by philkuz** [pixie-labs/pixie#32]
**Is your feature request related to a problem? Please describe.**
Would like to take a live view such as a service-level overview and drill down into details about individual Service-level views.

**Describe the solution you'd like**
e.g.
SLO violation occurs on front-end service. SRE/ SWE goes to live view for front-end, sees that traffic between front-end and user service has a huge spike in latency, wants to look at the user-service view to drill down.
**Describe alternatives you've considered**
Alternatives are to manually jump around dashboards and update the variables, could get very clunky and easy to mess up and hard to revert back 
**Additional context**

┆Issue is synchronized with this [Jira Bug](https://pixie-labs.atlassian.net/browse/PL-1658) by [Unito](https://www.unito.io/learn-more)

**Comment by htroisi** [comment]
Deeplinking is now implemented in Pixie's [Live UI](https://work.withpixie.ai/).
