### ISSUE TITLE
MySQL Live View

### ISSUE THREAD

**Issue by philkuz** [pixie-labs/pixie#33]
**Describe the question you are looking to answer**
Analyze the statistics of a service's MySQL connection. 
Should include latency of requests over time 

**Example scenario**
Service experiences SLO violations, can't diagnose problem by looking at services that are dependent on, want to look at database interactions. Turns out database request latencies are spiking, can then switch to another live view to see the rates of database interactions across all services in the cluster and can take action appropriately.

**Desired output**
Output Widgets
1. L
2. E
3. T
4. (Stretch) Top-K queries sent 

**Desired collaboration scheme**

- Do you want to share this view with your team (yes/no)? yes
- Do you want to persist this view in your team's git repo (yes/no)? yes
- Do you want to persist this view in pixie-community's git repo (yes/no)? yes

**(Optional) Draft scripts**
I think we can adapt the service_info view to do this as well.
```
###############################################################
# The following can be edited to k8s object and name to match.
###############################################################
# The Kubernetes object to filter on.
#    Options are ['pod', 'service']
k8s_object = 'pod'

# If you want to filter the object by name, enter the partial
# or full name here.
match_name = 'sock-shop'

# Names of output columns
src_name = 'client'
dest_name = 'server'
###############################################################
ip = 'remote_addr'
df = px.DataFrame(table='mysql_events', start_time='-60s')

df[k8s_object] = df.ctx[k8s_object]
df = df[df[k8s_object] != '' and px.contains(df[k8s_object], match_name)]
#px.display(df.head(100))
df = df.groupby([k8s_object, ip]).agg(count=(ip, px.count))

df[src_name] = df[k8s_object]
df[dest_name] = df[ip]
df['pod_id'] = px.ip_to_pod_id(df[ip])
df['requestor_pod'] = 	px.pod_id_to_pod_name(df.pod_id)
# Enable if you want pod name
df['requestor_service'] = 	px.pod_id_to_service_name(df.pod_id)
px.display(df[[src_name, dest_name, 'requestor_pod', 'count']])
```

┆Issue is synchronized with this [Jira Task](https://pixie-labs.atlassian.net/browse/PP-1659) by [Unito](https://www.unito.io/learn-more)

**Comment by htroisi** [comment]
This information is now available in Pixie's [px/mysql_stats](https://github.com/pixie-labs/pixie/tree/main/pxl_scripts/px/mysql_stats). This script calculates the latency, error rate, and throughput of a pod's MySQL requests.

@philkuz do you think it would be useful for me to add Top-k queries sent?

**Comment by htroisi** [comment]
Closing this issue because we now scripts specific to database interactions which include LET metrics: [mysql_stats](https://github.com/pixie-labs/pixie/blob/main/pxl_scripts/px/mysql_stats/mysql_stats.pxl), [pgsql_stats](https://github.com/pixie-labs/pixie/blob/main/pxl_scripts/px/psql_stats/pgsql_stats.pxl), [cql_stats](https://github.com/pixie-labs/pixie/blob/main/pxl_scripts/px/cql_stats/cql_stats.pxl)
