### ISSUE TITLE
Overflow of Graphs not Viewable in Live View

### ISSUE THREAD

**Issue by philkuz** [pixie-labs/pixie#36]
**Describe the bug**
I have a table that doesn't show up in the live view. I have to zoom out to see them as I can't scroll down. 
**To Reproduce**
1. Go to `/live` 
2. Choose default script
3. Edit placement config on first graph by increasing height to 12 (shoudl be sufficient to push other graphs off the screen
4. Try to scroll to see the graphs below w/ no luck

**Expected behavior**
Be able to scroll or the window adjust graphs so they are visible.

**Screenshots**
Here's me increasing height to 12, and can't scroll to see other tables now.
![image](https://user-images.githubusercontent.com/5456019/77367782-1cea9600-6d18-11ea-86f4-06c4db472fcd.png)

**Logs**
n/a

**App information (please complete the following information):**
- Pixie version 0.1.21
- K8s cluster version: irrelevant

┆Issue is synchronized with this [Jira Bug](https://pixie-labs.atlassian.net/browse/PL-1662) by [Unito](https://www.unito.io/learn-more)

**Comment by htroisi** [comment]
This appears fixed on prod. @philkuz - let me know if this is still an issue for you.
