### ISSUE TITLE
Path expansion issue in install script creates a bad directory for px install

### ISSUE THREAD

**Issue by tuxology** [pixie-labs/pixie#43]
**Describe the bug**
Wrong installation path on Linux with installer script

**To Reproduce**
1. `curl -fsSL https://withpixie.ai/install.sh | bash`
2. Logs show the following

```
- PX CLI has been installed to: INSTALL_PATH=${INSTALL_PATH:-${DEFAULT_INSTALL_PATH}}. Make sure this directory is in your PATH.
```

It creates a directory with that name and pixie is inside:

```
$ ls INSTALL_PATH=\$\{INSTALL_PATH:-\$\{DEFAULT_INSTALL_PATH\}\} 
px
```

**Expected behavior**
1. The install script should either prompt for installation path.
2. If non-interactive mode is used as a standard, it should expect an installation path arg or should install the bin in the same directory from where it is called

**Version/info**
```
[0000]  INFO Pixie CLI
0.1.25+Distribution.59beb5c.20200326150522.1
```

**Additional context**
Running on Elementary OS (Ubuntu 18.04 derivative) with `zsh`. But pixie spawns bash for install script

┆Issue is synchronized with this [Jira Bug](https://pixie-labs.atlassian.net/browse/PL-1691) by [Unito](https://www.unito.io/learn-more)

**Comment by zasgar** [comment]
Closing as stale issue
