### ISSUE TITLE
Pin point jvm memory leak

### ISSUE THREAD

**Issue by ishanmkh** [pixie-labs/pixie#46]
// filing on behalf of @tuxology so that we can track 

**Example scenario**
So here is what happened. We have a runtime service which customers use - its an agent that gets attached to customer's java apps. Javaagents are notorious - for obvious reasons (security and performance. But apparently someone in industry decided it was ok to use them. So we shipped an agent which accidently had a memory leak (edited) JVM handles the memory and would run GC intermittently

We cold not identify this as part of customer's container (which had lots of workloads). So I had to isolate it locally and the moment i saw the sawtooth waveform, I knew from experience what it is. 

https://twitter.com/tuxology/status/1019317134743048192?s=20

https://twitter.com/tuxology/status/1136683456451055617?s=20

I built the infra to discover this using grafana + periodic tests. So next time we discovered it faster (see grafana charts). If Px was available, we would have been able to discover this in production I think. By specifically collecting memory metrics filtered by the ppid in container

**Desired output**
Output Widgets
1. Recreate this scenario with a sample java app
2. Explain what is happening
3. Show how we can identify with VirtualVM locally
4. Show how we can identify it when its deployed in a cluster by pinpoint analysis with `px1

**Desired collaboration scheme**

- Do you want to share this view with your team (yes/no)? n/a
- Do you want to persist this view in your team's git repo (yes/no)?  n/a
- Do you want to persist this view in pixie-community's git repo (yes/no)? n/a

**Additional requirements**
n/a

**(Optional) Draft scripts**
n/a

┆Issue is synchronized with this [Jira Bug](https://pixie-labs.atlassian.net/browse/PL-1694) by [Unito](https://www.unito.io/learn-more)

**Comment by zasgar** [comment]
Closing as stale issue
