### ISSUE TITLE
Can't deploy Pixie with Kind 

### ISSUE THREAD

**Issue by ishanmkh** [pixie-labs/pixie#60]
**Describe the bug**
PEMs doesn't collect any data  (process_stats, network_stats etc)

**To Reproduce**
1. create kind cluster
2. install px
3. deploy pixie
4. run any scripts

**Expected behavior**
Should deploy as expected

**Screenshots**
n/a

**Logs**
[pixie_logs_20200424021521.zip](https://github.com/pixie-labs/pixie/files/4526457/pixie_logs_20200424021521.zip)

**App information (please complete the following information):**
- Pixie version
- K8s cluster version

**Additional context**

**Comment by oazizi000** [comment]
What system was this run on? The logs suggest that this was Kind on top of Mac. Can you confirm?

**Comment by ishanmkh** [comment]
@oazizi000  this was run on a mac.

**Comment by htroisi** [comment]
Pixie has decided to de-prioritize Kind support for the foreseeable future. You can see the full list of suppported k8s environments [here](https://docs.pixielabs.ai/installing-pixie/install-guides/).

**Comment by o6uoq** [comment]
@htroisi `kind` is the most popular way to run Kubernetes locally - what was the thinking behind deciding to deprioritize?

**Comment by htroisi** [comment]
@o6uoq the difficulty with supporting `kind` is that it runs K8s clusters inside Docker container "nodes". More context below:

> Pixie requires access to the host kernel for eBPF. Environments where k8s is running run on bare-metal or on a VM (e.g. kvm2) meet this requirement, and so that's why Pixie works. In environments where there's an extra containerization layer, Pixie can't currently properly punch through to the host. That's why things like kind are not yet supported.
