### ISSUE TITLE
Documentation error in installation instructions

### ISSUE THREAD

**Issue by elsonrodriguez** [pixie-labs/pixie#65]
**Describe the bug**
Documentation here has incorrect curl syntax:

https://docs.pixielabs.ai

`./bash -c "$(curl-fsSL https://withpixie.ai/install.sh)"`

Correct syntax for most systems would be:

`bash -c "$(curl -fsSL https://withpixie.ai/install.sh)"`

**Comment by zasgar** [comment]
@elsonrodriguez, thanks for pointing this out. It has been fixed and deployed in the latest docs.
