### ISSUE TITLE
PodSecurityPolicies prevent pixie pods from getting deployed. 

### ISSUE THREAD

**Issue by zasgar** [pixie-labs/pixie#71]
This was observed on a cluster deployed using https://github.com/gravitational/gravity. The exact error message is: 

Vizier Version: 0.3.12

```
  Warning  FailedCreate  4m44s (x18 over 15m)  replicaset-controller  Error creating: pods "vizier-cloud-connector-56f65959fb-" is forbidden: unable to validate against any pod security policy: []
```

We can probably fix this by adding a security policy for pixie deployed pods.

**Comment by htroisi** [comment]
A Pod Security Policy was added in our latest Vizier version (0.5.3), but were unable to repro the problem above to confirm the fix. If anyone runs into this problem again, please let us know and we can investigate further.
