### ISSUE TITLE
Add a flag to the `deploy` subcommand to tolerate taints.

### ISSUE THREAD

**Issue by elsonrodriguez** [pixie-labs/pixie#73]
**Is your feature request related to a problem? Please describe.**
Some clusters use taints and tolerations for workload isolation or other scheduling concerns. This can prevent the vizier-pem pods from scheduling to some nodes.

**Describe the solution you'd like**
I'd like a flag to enable the vizier-pems to schedule everywhere. Something like a `--tolerate` flag on the `deploy subcommand` that creates the vizier-pem daemonset with these tolerations:

```
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
```
**Describe alternatives you've considered**
I've patched the daemonset after deployment to get around this. If this is deployed as a permanent fixture on the cluster, this would also be handled elsewhere.

**Comment by ishanmkh** [comment]
thanks @elsonrodriguez for the feedback. We've received feedback for configurable deploys over taints from other customer deploying in enterprise environments and is in our plans. we'll report back with an ETA on this soon.

**Comment by htroisi** [comment]
@elsonrodriguez - We have updated our PEM's tolerations so that they can deployed on tainted nodes. This was included in vizier version 0.5.3.

**Comment by ermusthofa** [comment]
hi @htroisi , thank you to add this feature! anyway, do you have any documentation to set tolerations ?

**Comment by htroisi** [comment]
Hi @ermusthofa - Thanks for asking! The title of this issue was misleading (and is now fixed). Pixie's general tolerations should allow the vizier-pem nodes to run on both tainted and untainted nodes without setting any deploy flags. Please let me know if you notice any issues with PEMs not getting scheduled on certain nodes and we'd be happy to take a look.

**Comment by ermusthofa** [comment]
Hi @htroisi , thanks for the clarification. I believe it will runs on my tainted nodes now. thank you! :bow:

**Comment by Semmix** [comment]
Pixie is only deploying to Untainted nodes still for me, is there anything im missing ?
